Adjust the creator ID filter
eventespresso/eea-multisite pull request #9
Opened 2020-10-27 18:23 UTC by knazart

## Problem this Pull Request solves

This is a part of https://github.com/eventespresso/eventsmart.com-website/issues/793

As mentioned in [this comment](https://github.com/eventespresso/eventsmart.com-website/issues/793#issuecomment-716662206), `FHEE__EEH_Activation__get_default_creator_id__pre_filtered_id` filter added in this addon was a part of a DMS requirement, and I'm not sure it's really needed anymore as a permanent filter as it adds a few more redundant queries to the `usermeta` table on each sub site on a lot of requests.

This PR also fixes the `while` statement, where the `$user_id` that's passed back is usually a `null`.

## How has this been tested

Testing will be done on MENW and the notes will be provided in a PR created as a part of this plugin update. The PR will be listed here after this PR is reviewed.

2020-10-27 18:33 UTC, knazart commented
@tn3rb would you have any thoughts here ? If any.. 

The default (EE Core) query for the "default blog creator" is:
```
SELECT user_id FROM ssusermeta WHERE meta_key = 'ss24330_capabilities' AND meta_value LIKE '%administrator%' ORDER BY user_id ASC LIMIT 0,1
```

and the filter added in this Multisite plugin kinda replaces it with:
```
SELECT user_id from ssusermeta WHERE meta_key='primary_blog' AND meta_value='24330' ORDER BY user_id ASC LIMIT 0, 1
SELECT user_id from ssusermeta WHERE meta_key='primary_blog' AND meta_value='24330' ORDER BY user_id ASC LIMIT 1, 1
```

But the logic in that `while` statement had a bug in my opinion, and was always returning `null`. My local testing confirmed this. Because when the `$user_id` breaks the loop it's already a `null` and can't really be used or useful.

Both of those queries usually return the same user ID.

The Ticket with work on this filter is not very informative: https://events.codebasehq.com/projects/event-espresso/tickets/6855

Oh, and the tests failed. Hmm.

2020-10-27 20:23 UTC, tn3rb commented
>  the filter added in this Multisite plugin kinda replaces it with:

ya I don't understand the purpose of running that query in a do while loop ?!?!? 
(I realize you didn't write that though)

like... why not just grab the first 10 users for that blog and then loop through those until you find an admin?!?!?
Multiple queries will take longer than one query that returns a bunch of records.


> the logic in that while statement had a bug in my opinion, and was always returning null

hmmmm... not seeing why it would ALWAYS return `null`, unless I'm missing something...

here's how I see that logic working:

- if no records are found on the first run of the query, then:

	- the do while should break because the first clause in `while ($user_id && ! user_can($user_id, $role_to_check))` should fail

	- `$_default_creator_id` should NOT get set

 	- and the function should return `null`.

- if the first result returned from the query IS a user, then:

	- the first clause in `while ($user_id && ! user_can($user_id, $role_to_check))` should pass

	- if the user HAS the required role then the call to `user_can()` will return `true`, BUT that will get toggled to `false` because of the extra NOT in there, which means that the do while should exit.

	- `$_default_creator_id` SHOULD get set

 	- and the function should return the correct user id

- if the first result returned from the query is a user BUT the user does NOT have the required role, then:

	- the call to `user_can()` will return `false` which then gets toggled to `true` because of the extra NOT in there, which means that the do while should run AGAIN since both results evaluated to `true` 

so those are the only possibilities for the first pass through the do while:

- no users = exit loop + return null
- user matching required role = exit loop + return user id
- user WITHOUT required role = continue loop 

Now on subsequent loops it will essentially repeat the above until it either finds a user with the required role or run out of users.

Not seeing how that would return null for you every time. 🤷‍♂️ 

What's insane is that if the site has users but NONE of them have the required role, then that loop will keep firing off single queries until it runs out of users. I don't know if there is any chance of that happening, but there is nothing in that code to prevent that.

Anyways, i think the following is fine, and the only change I would make (without TOTALLY changing things) would be to remove the unnecessary else clause after the function return, ie:

```php
$offset = 0;
$role_to_check = apply_filters('FHEE__EE_Multisite__get_default_creator_id__role_to_check', 'administrator');
do {

    $query = $wpdb->prepare(
    	"SELECT user_id from {$wpdb->usermeta} WHERE meta_key='primary_blog' "
    	. "AND meta_value=%s ORDER BY user_id ASC LIMIT %d, 1",
    	get_current_blog_id(),
    	$offset++
    );

    $user_id = $wpdb->get_var($query);

} while ($user_id && ! user_can($user_id, $role_to_check));

$user_id = (int) apply_filters('FHEE__EE_Multisite__get_default_creator_id__user_id', $user_id);

if ($user_id) {
    self::$_default_creator_id = $user_id;
}

return self::$_default_creator_id;
```

but I might be missing something.

Now that said, because running a query inside of a do while loop seems like a big recursive "OOF!" waiting to happen, I would be tempted to try and rewrite the query so that it can just be done once. That's NOT easy however because of the stupid way that WordPress tracks capabilities. Off the top of my head, I'm thinking you could try self joining to the user meta table and use a `%LIKE% condition on the `meta_value` fields where the `meta_key='wp_capabilities'`

So maybe something like:

```php
$query = $wpdb->prepare(
    "SELECT u1.user_id
    FROM wp_usermeta AS u1
    INNER JOIN wp_usermeta AS u2
        ON u1.user_id = u2.user_id
    WHERE u1.meta_key='primary_blog'
        AND u1.meta_value=%s
        AND u2.meta_key=''wp_capabilities''
        AND u2.meta_value LIKE '%%s%'
    ORDER BY user_id ASC
    LIMIT 1"
    get_current_blog_id(),
    $role_to_check
);
```
 
but no guarantees that that would work since `'%%s%'` looks like it could easily cause issues 😆
might also need to move some and/or all of those WHERE clauses into the JOIN statement.

2020-10-27 20:37 UTC, tn3rb requested changes
Sorry but there's a potential issue in the changes you've made.

2020-10-27 20:37 UTC, tn3rb commented on EE_Multisite.class.php
> +            self::$_default_creator_id = $userIdToPass;
after looking at this some more...

the code you've added is not correct because it could allow a user that does NOT have the required role to be set as the default creator!

Why?

Because you are taking any valid user ID and saving it to `$userIdToSave`, but the call to `user_can()` is using `$user_id` NOT `$userIdToSave`.

IF that query runs through all of the users but does NOT find any that have the required role, `$userIdToSave` could still be set to a valid user ID, which would then get passed along to the filter and then saved as $_default_creator_id, but `$userIdToSave` may not have passed the `user_can()` check.

All you need to imagine is a scenario where the site has 1 user but that user does NOT have the required role to be considered the default creator.

SO on the first pass through the loop, that user is found, their user id gets saved to `$userIdToSave`, but the `user_can()` check fails, causing the loop to execute again. But on the second pass, the query returns null, which does NOT overwrite `$userIdToSave` since we only capture valid user ids with that variable. However, since the loop no longer executes, we continue on with the logic and pass the value of `$userIdToSave` to the filter... even though that user had failed the `user_can()` check. Then assuming the filter doesn't change anything, we get the same `$userIdToSave` back and set that user as the default creator despite them not having the required role.

So my apologies, but some of what you've added here can't be merged.

I'm guessing the issues you had with the function returning null had to do with the permissions and not the logic of the function itself.

2020-10-27 20:48 UTC, knazart commented on EE_Multisite.class.php
> +            self::$_default_creator_id = $userIdToPass;
> the code you've added is not correct because...

Yes yes, I see that now. I did a quick PR before heading away for a bit. Didn't expect you to review this so quickly 🙂

> So my apologies, but some of what you've added here can't be merged.

No apologies required. This is plainly incorrect as with these changes I didn't account for the role check. The fail I experienced is related to the admin cap fail on my user for some reason... Not the loop.
Sorry for sending you on a "wild hunt", ahead of time.

2020-10-27 20:54 UTC, knazart commented
> seems like a big recursive "OOF!" waiting to happen

YES. And that's why I'm surfing through this code, because we already have "out of memory" issues on ES where this query loop is querying an already massive usermeta table.

Thanks for the suggestions.

2020-10-27 21:41 UTC, tn3rb commented on EE_Multisite.class.php
> +            self::$_default_creator_id = $userIdToPass;
> No apologies required. 

I'm sorry but I'm Canadian and am legally required to apologize 🍁

2020-10-27 21:51 UTC, tn3rb commented
> we already have "out of memory" issues on ES where this query loop is querying an already massive usermeta table.

you could add a conditional like:

```php
if ( $offset > 10 ) {
	// log timestamp and offset
}
```

after the loop just to see how many records that query is actually looping through.

Then at least you'll know whether this was the culprit, however your other change in this PR might fix the issue regardless.

2020-10-27 22:15 UTC, knazart commented on EE_Multisite.class.php
> +            self::$_default_creator_id = $userIdToPass;
😆👍

2020-10-28 00:11 UTC, tn3rb approved these changes
KOOL!
let's hope that was the cause of those massive spikes (would make sense if that's what it was)

2020-10-28 00:11 UTC, tn3rb commented on EE_Multisite.class.php
> +        $blogId = get_current_blog_id();
nice 👍 

was going to suggest this (especially considering it was in a loop) but forgot

2020-10-28 00:11 UTC, tn3rb commented on EE_Multisite.class.php
> +        );
did this actually work?
that's awesome if it did!!!

2020-10-28 11:44 UTC, knazart commented on EE_Multisite.class.php
> +        );
Yes. I've reviewed the query and tested it, it works. The only thing that differs is that `user_can()` strictly check for an `administrator` role, wheres this query will also accept `event_administrator` roles, which I believe is more suitable because when a site is created the site admin is of "Event Administrator" role. That's also why I was constantly getting a `null` I mentioned above - because there are no `administrator` roles for sub-site users, i.e. admins are event admins. This also kinda confirms it's still a DMS requirement from 2014 (maybe we used `administrator` roles back then ?). So... maybe I should make that be a more strict role check.

2020-10-28 13:16 UTC, knazart commented
Considering the https://github.com/eventespresso/eea-multisite/pull/9#discussion_r513377910, one more review please.

2020-10-28 17:40 UTC, tn3rb approved these changes
ahhh I see what you mean now... didn't grok what you meant by "make the query strict" 👍 

ya this looks great

2020-10-28 18:59 UTC, merged